### ISSUE TITLE
White objects on the sea

### ISSUE THREAD

**Issue by turret001** [Wolfee-J/MTA-Vice-City#2] opened 2020-06-30 13:06 UTC
Pos: 335.55762, -1746.67297, 4.45000

these white objects appeared on the sea.
![vcbug2](https://user-images.githubusercontent.com/24281147/86129459-67d03280-baeb-11ea-86e6-20c398555e55.png)

also, fishes are not loaded properly as well I think
![vcbug](https://user-images.githubusercontent.com/24281147/86129485-71f23100-baeb-11ea-8df1-009ed26b7bab.png)

I don't know if this is related to MTA-Streamer or MTA-Vice-City. Here's the order that I started the resources:

1. MTA-Stream
2. VC2
3. VCLightGen
4. VCMini

Client version:   v1.5.7-release-20582 
Server version: v1.5.7-release-20348

**Comment by turret001** [comment] 2020-06-30 13:09
after doing a /stopall and starting MTA-Stream + VC2, white stuff in sea disappeared but some other objects lost their textures
![image](https://user-images.githubusercontent.com/24281147/86129913-14121900-baec-11ea-9722-52f7730a1964.png)

**Comment by Wolfee-J** [comment] 2020-06-30 17:04
Duplicate of https://github.com/Wolfee-J/MTA-Stream/issues/5 more related to streamer.

**Closed as completed by Wolfee-J** 2020-06-30 17:04 UTC
Labels: bug
